// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtgrvcskrmonfufuytjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0Z3J2Y3Nrcm1vbmZ1ZnV5dGpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NTk5MzcsImV4cCI6MjA2OTAzNTkzN30.J0uEHGDq6hl_o4SpySiwC7dML-EYT2wXhfZNVyoK_d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});